# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='待编辑', max_length=128, verbose_name='房间名字'),
        ),
    ]
